from spike.ConnectSFTP import ConnectSFTP
from spike.ConnectGoogleDrive import ConnectGoogleDrive
from spike.ConnectGoogleCloudStorage import ConnectGoogleCloudStorage
from spike.FileCMD import FileCMD