from spike.ConnectSFTP import ConnectSFTP
from spike.ConnectGoogleDrive import ConnectGoogleDrive
from spike.ConnectGoogleCloudStorage import ConnectGoogleCloudStorage
from spike.my_sum import my_sum
