from DataManagement.ConnectSFTP import ConnectSFTP
from DataManagement.ConnectGoogleDrive import ConnectGoogleDrive
from DataManagement.ConnectGoogleCloudStorage import ConnectGoogleCloudStorage
from DataManagement.FileCMD import FileCMD
from DataManagement.UploadFolderToGD import UploadFolderToGD
from DataManagement.DownloadFolderFromGD import DownloadFolderFromGD